FROM postgres:latest

ENV POSTGRES_DB=philo-graph
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=abc-123

# Copy an initialization SQL script to the container
COPY init.sql /docker-entrypoint-initdb.d/

# Expose port 5432
EXPOSE 6667
